apiVersion: v1
kind: Namespace
metadata:
  name: dbic

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: dbic
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/part-of: dbic
      app.kubernetes.io/name: ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ui
        app.kubernetes.io/version: "1"
        app.kubernetes.io/component: service
        app.kubernetes.io/part-of: dbic
        app.kubernetes.io/created-by: suchcodewow
      annotations:
        owner: Frontend Team
        chat-channel: dev-team-services
    spec:
      containers:
        - name: ui
          image: { { .Values.image } }
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: ui
          env:
            - name: DT_CUSTOM_PROP
              value: "project=dbic service=ui"
            - name: PORT
              value: "3000"

---
apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: dbic
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: dnsplaceholder
  labels:
    app.kubernetes.io/part-of: dbic
    app.kubernetes.io/name: ui
spec:
  ports:
    - port: 80
      targetPort: 3000
      name: ui
  selector:
    app.kubernetes.io/part-of: dbic
    app.kubernetes.io/name: ui
  type: LoadBalancer
